apiVersion: v1
kind: Pod
metadata:
  name: g1-output-reader-1
spec:
  containers:
  - name: output-reader-container-1
    image: ubuntu:20.04
    command: ["/bin/bash", "-c", "--"]
    args: ["while true; do sleep 30; done;"]
    volumeMounts:
    - mountPath: /g1_wandb
      name: g1-volume
  volumes:
  - name: g1-volume
    persistentVolumeClaim:
      claimName: g1-volume
  restartPolicy: Never

