apiVersion: batch/v1
kind: Job
metadata:
  name: jianhan-g1-training-quad-37dof
spec:
  template:
    spec:
      containers:
      - name: g1-container
        image: rchal97/complex_loco_preview4
        command:
          - "/bin/bash"
          - "-c"
          - |
            cd /workspace
            conda create -y -n humanoid python=3.8 &&
            source activate humanoid &&
            # cd ~ &&
            pip3 install torch==1.10.0+cu113 torchvision==0.11.1+cu113 torchaudio==0.10.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html &&
            git clone https://github.com/Kingspenguin/g1.git &&
            cd g1 &&
            git checkout main &&
            cd isaacgym/python &&
            pip install -e . &&
            cd ../.. &&
            cd rsl_rl &&
            pip install -e . &&
            cd .. &&
            cd legged_gym &&
            pip install -e . &&
            cd .. &&
            pip install "numpy<1.24" pydelatin wandb tqdm opencv-python ipdb pyfqmr flask dill gdown &&
            conda deactivate &&
            source activate humanoid &&
            cd legged_gym/legged_gym/scripts &&
            wandb login a14459c6f0305e04b9b7db0721941580070fcdd1 &&
            /opt/conda/envs/humanoid/bin/python train.py g1_train_quad_37  --no_wandb --task g1

        env:
        - name: WANDB_API_KEY
          value: "a14459c6f0305e04b9b7db0721941580070fcdd1"

        volumeMounts:
        - mountPath: /g1_jianhan_quad
          name: g1-volume-quad
        resources:
          limits:
            nvidia.com/gpu: "1"
            memory: "32G"
            cpu: "4"
          requests:
            nvidia.com/gpu: "1"
            memory: "32G"
            cpu: "4"
      restartPolicy: Never
      volumes:
      - name: g1-volume-quad
        persistentVolumeClaim:
          claimName: g1-volume-quad

